[project]
name = "django-turntable"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Ryan Thomson" },
]
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.ruff.format]
line-ending = "lf"
quote-style = "single"

[tool.ruff.lint]
extend-select = ["B", "I", "UP"]
