[project]
name = "django-turntable"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Ryan Thomson" },
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.0",
]

[dependency-groups]
dev = [
    "debugpy==1.8.20",
    "django-stubs==5.2.9",
    "pyright==1.1.408",
    "ruff==0.15.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.pyright]
include = ["src", "tests"]
strict = ["src"]

[tool.ruff.format]
line-ending = "lf"
quote-style = "single"

[tool.ruff.lint]
extend-select = ["B", "I", "UP"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
